[plugins]
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.0.21" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
spring-boot = { id = "org.springframework.boot", version = "3.3.5" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }

[libraries]
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version = "5.9.1" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.9.0" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = "1.9.0" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.11.3" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version = "5.11.3" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.11.3" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.16" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
spring-context = { group = "org.springframework", name = "spring-context", version = "6.1.14" }
spring-web = { group = "org.springframework", name = "spring-web", version = "6.1.14" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version = "3.3.5" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = "2.18.0" }
kotlin-deeplearning-api = { group = "org.jetbrains.kotlinx", name = "kotlin-deeplearning-api", version = "0.5.2" }
kotlin-deeplearning-impl = { group = "org.jetbrains.kotlinx", name = "kotlin-deeplearning-impl", version = "0.5.2" }
kotlin-deeplearning-onnx = { group = "org.jetbrains.kotlinx", name = "kotlin-deeplearning-onnx", version = "0.5.2" }
kotlin-deeplearning-dataset = { group = "org.jetbrains.kotlinx", name = "kotlin-deeplearning-dataset", version = "0.5.2" }
kotlin-deeplearning-tensorflow = { group = "org.jetbrains.kotlinx", name = "kotlin-deeplearning-tensorflow", version = "0.5.2" }
